# Generated by Django 4.1.9 on 2023-05-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='photo',
            field=models.ImageField(default='noimage.png', upload_to='web/Template/media/'),
        ),
    ]
