# Generated by Django 4.1.9 on 2023-05-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_garage_photo_alter_producto_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='photo',
            field=models.ImageField(default='/Template/media/noimage.png', upload_to='Template/media/'),
        ),
    ]
